# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 05:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_recurring', models.CharField(blank=True, max_length=127, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('reason', models.TextField(default='Not stated')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
