# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20170517_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_end',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_start',
            field=models.TimeField(db_index=True, default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('date', 'time_start')]),
        ),
    ]
